# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

# Examples:

#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#

League.create(name: "League1")

User.create(username: "Owner1", user_type: "owner", password_digest: "abc123")
User.create(username: "Owner2", user_type: "owner", password_digest: "abc123")
User.create(username: "Owner3", user_type: "owner", password_digest: "abc123")
User.create(username: "Analyst1", user_type: "analyst", password_digest: "abc123")
User.create(username: "Analyst2", user_type: "analyst", password_digest: "abc123")
User.create(username: "Analyst3", user_type: "analyst", password_digest: "abc123")


Team.create(name: "Team1", owner_id: 1, league_id: 1)
Team.create(name: "Team2", owner_id: 2, league_id: 1)
Team.create(name: "Team3", owner_id: 3, league_id: 1)

Player.create(name: "Tom Brady", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/sfehmfwtg9i5gdcpqzgf")
Player.create(name: "Aaron Rodgers", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/dwozjxa5zlhlzhu3urxy")
Player.create(name: "Drew Brees", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/nnhvcikd59brb8jkglxj")
Player.create(name: "Ezekiel Elliot", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/mphucnl2h80vne21dzik")
Player.create(name: "Austin Ekeler", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/rpknwsvkh8wy6mdzg5og")
Player.create(name: "Saquon Barkley", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/yimxr0tykw7u3aogj60u")
Player.create(name: "Michael Thomas", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/liuzt7209f2hqa9mu1zw")
Player.create(name: "Davante Adams", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/if8ugbd2i2lqbilqard3")
Player.create(name: "Mike Evans", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/hp7exmuqylysgife5p9m")
Player.create(name: "Julio Jones", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/rwmuvncrjw14oik8unyy")
Player.create(name: "Christian McCaffrey", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/fbmd42eh96156aug14kp")
Player.create(name: "Alvin Kamara", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/rubeyrjz53yacwyjgycx")
Player.create(name: "Derrick Henry", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/f5kj56yln1s0qlpdhbxu")
Player.create(name: "Dalvin Cook", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/sxhuurbjysw8vxgj8arg")
Player.create(name: "Tyreek Hill", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/bsgiiaeo4l2arlrw1sbz")
Player.create(name: "Deandre Hopkins", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/zvgis3wkz7enb0b7rxs1")
Player.create(name: "Nick Chubb", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/m10y1skypqxyvigftdle")
Player.create(name: "Aaron Jones", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/fhg7hqiz87nyx1payjqh")
Player.create(name: "Chris Godwin", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/tj59ipzac4m2vagb3ki5")
Player.create(name: "Kenny Golladay", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_player_profile_landscape/f_auto/league/ahae4bckoirec4nx0s9c")
Player.create(name: "Joe Mixon", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/y2dbpo1i0lnnnyobip7b")
Player.create(name: "Mike Evans", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/hp7exmuqylysgife5p9m")
Player.create(name: "Amari Cooper", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/mo6ymonnhq8n8jg4sgcx")
Player.create(name: "Travis Kelce", position: "TE", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/b5hgyjflobudjoic3scp")
Player.create(name: "Josh Jacobs", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/docmktgq1ubvu87ltcco")
Player.create(name: "George Kittle", position: "TE", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/n5dvz5zxymahzxnl4cq3")
Player.create(name: "Cooper Kupp", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/kfxoxgxotskc1ys37pxr")
Player.create(name: "Miles Sanders", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/kwkhcqjrcab6tqybo94d")
Player.create(name: "Chris Carson", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/e0ujyqabb4tnqn0jusy9")
Player.create(name: "Patrick Mahomes", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/khrzmfjyof1ef9d1cftm")
Player.create(name: "Juju Smith-Schuster", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/sp4gz46f1rkpksvsmtg7")
Player.create(name: "Adam Thielen", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ivv1msxgjhj02lwmkwtj")
Player.create(name: "Robert Woods", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_desktop/f_auto/league/yhevkmorup1plsdhwar0")
Player.create(name: "Lamar Jackson", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/rojvfogdbjpld2ldvdop")
Player.create(name: "Melvin Gordon", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/en0ul7l1m9aqf7wffufg")
Player.create(name: "Allen Robinson", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/pph9jgnrnnlilxz8xhd9")
Player.create(name: "Kenyan Drake", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/cnkha97t7evnzybhqsta")
Player.create(name: "Calvin Ridley", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/hs5jmrnhypokqvyxdzk7")
Player.create(name: "AJ Brown", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ucz9frks91kdccmgkkct")
Player.create(name: "Odell Beckham", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/yzjnhcodduxtsqobvmpe")
Player.create(name: "Clyde Edwards-Helaire", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ldgjalogqzti76pmqbw1")
Player.create(name: "Leonard Fournette", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "DJ Moore", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Tyler Lockett", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Devante Parker", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Leveon Bell", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Todd Gurley", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Mark Andrews", position: "TE", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Keenan Allen", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Stefon Diggs", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "James Conner", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Courtland Sutton", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "TY Hilton", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "DJ Chark", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Devin Singletary", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Raheem Mostert", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Zach Ertz", position: "TE", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Dak Prescott", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "DK Metcalf", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Terry McLaurin", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "David Johnson", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "James White", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Russell Wilson", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Darren Waller", position: "TE", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Deebo Samuel", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "D'Andre Swift", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Kyler Murray", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Mark Ingram", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Tyler Boyd", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Evan Engram", position: "TE", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Deshaun Watson", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Jarvis Landry", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Michael Gallup", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Hunter Henry", position: "TE", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Cam Akers", position: "RB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Josh Allen", position: "QB", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Rob Gronkowski", position: "TE", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Austin Hooper", position: "TE", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Julian Edelman", position: "WR", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/ts21do870bsfb6iiepsh")
Player.create(name: "Stephen Gostkowski", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/nqi0psnge6kkglcspabo")
Player.create(name: "Justin Tucker", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/fkbbgxqqvf7fn3qycm8n")
Player.create(name: "Harrison Butker", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/fkbbgxqqvf7fn3qycm8n")
Player.create(name: "Rodrigo Blankenship", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/fkbbgxqqvf7fn3qycm8n")
Player.create(name: "Matt Prater", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/fkbbgxqqvf7fn3qycm8n")
Player.create(name: "Steven Haushcka", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/fkbbgxqqvf7fn3qycm8n")
Player.create(name: "Sebastian Janikowski", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/fkbbgxqqvf7fn3qycm8n")
Player.create(name: "Adam Vinatieri", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/fkbbgxqqvf7fn3qycm8n")
Player.create(name: "Jake Elliot", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/fkbbgxqqvf7fn3qycm8n")
Player.create(name: "Younghoe Koo", position: "K", photo_url: "https://static.www.nfl.com/image/private/t_headshot_tablet/f_auto/league/abkoyjrdrec9eub1pmzm")
Player.create(name: "Bears", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/CHI.svg")
Player.create(name: "Steelers", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/PIT.svg")
Player.create(name: "Eagles", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/PHI.svg")
Player.create(name: "Cardinals", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/ARI.svg")
Player.create(name: "Chiefs", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/KC.svg")
Player.create(name: "Saints", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/NO.svg")
Player.create(name: "Rams", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/LA.svg")
Player.create(name: "Chargers", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/LAC.svg")
Player.create(name: "Ravens", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/BAL.svg")
Player.create(name: "Falcons", position: "D", photo_url: "https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/ATL.svg")






100.times do
  PlayerTeam.create(player_id: Player.all.sample.id, team_id: Team.all.sample.id)
end

250.times do
  Ranking.create(analyst_id: rand(4..6), player_id: Player.all.sample.id, ranking: rand(1..100))
end
