# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

Examples:

  movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
  Character.create(name: 'Luke', movie: movies.first)


League.create(name: "League1")

User.create(username: "Owner1", user_type: "owner", password_digest: "abc123")
User.create(username: "Owner2", user_type: "owner", password_digest: "abc123")
User.create(username: "Owner3", user_type: "owner", password_digest: "abc123")
User.create(username: "Analyst1", user_type: "analyst", password_digest: "abc123")
User.create(username: "Analyst2", user_type: "analyst", password_digest: "abc123")
User.create(username: "Analyst3", user_type: "analyst", password_digest: "abc123")


Team.create(name: "Team1", owner_id: 1, league_id: 1)
Team.create(name: "Team2", owner_id: 2, league_id: 1)
Team.create(name: "Team3", owner_id: 3, league_id: 1)

Player.create(name: "Tom Brady", position: "QB")
Player.create(name: "Aaron Rodgers", position: "QB")
Player.create(name: "Drew Brees", position: "QB")
Player.create(name: "Ezekiel Elliot", position: "RB")
Player.create(name: "Austin Ekeler", position: "RB")
Player.create(name: "Saquon Barkley", position: "RB")
Player.create(name: "Michael Thomas", position: "WR")
Player.create(name: "Davante Adams", position: "WR")
Player.create(name: "Mike Evans", position: "WR")
Player.create(name: "Julio Jones", position: "WR")
Player.create(name: "Christian McCaffrey", position: "WR")
Player.create(name: "Alvin Kamara", position: "RB")
Player.create(name: "Derrick Henry", position: "RB")
Player.create(name: "Dalvin Cook", position: "RB")
Player.create(name: "Tyreek Hill", position: "WR")
Player.create(name: "Deandre Hopkins", position: "WR")
Player.create(name: "Nick Chubb", position: "RB")
Player.create(name: "Aaron Jones", position: "RB")
Player.create(name: "Chris Godwin", position: "WR")
Player.create(name: "Kenny Golladay", position: "WR")
Player.create(name: "Joe Mixon", position: "RB")
Player.create(name: "Mike Evans", position: "WR")
Player.create(name: "Amari Cooper", position: "WR")
Player.create(name: "Travis Kelce", position: "TE")
Player.create(name: "Josh Jacobs", position: "RB")
Player.create(name: "George Kittle", position: "TE")
Player.create(name: "Cooper Kupp", position: "WR")
Player.create(name: "Miles Sanders", position: "RB")
Player.create(name: "Chris Carson", position: "WR")
Player.create(name: "Patrick Mahomes", position: "QB")
Player.create(name: "Juju Smith-Schuster", position: "WR")
Player.create(name: "Adam Thielen", position: "WR")
Player.create(name: "Robert Woods", position: "WR")
Player.create(name: "Lamar Jackson", position: "QB")
Player.create(name: "Melvin Gordon", position: "RB")
Player.create(name: "Allen Robinson", position: "WR")
Player.create(name: "Kenyan Drake", position: "RB")
Player.create(name: "Calvin Ridley", position: "WR")
Player.create(name: "AJ Brown", position: "WR")
Player.create(name: "Odell Beckham", position: "WR")
Player.create(name: "Clyde Edwards-Helaire", position: "RB")
Player.create(name: "Leonard Fournette", position: "RB")
Player.create(name: "DJ Moore", position: "WR")
Player.create(name: "Tyler Lockett", position: "WR")
Player.create(name: "Devante Parker", position: "WR")
Player.create(name: "Leveon Bell", position: "RB")
Player.create(name: "Todd Gurley", position: "RB")
Player.create(name: "Mark Andrews", position: "TE")
Player.create(name: "Keenan Allen", position: "WR")
Player.create(name: "Stefon Diggs", position: "WR")
Player.create(name: "James Conner", position: "RB")
Player.create(name: "Courtland Sutton", position: "WR")
Player.create(name: "TY Hilton", position: "WR")
Player.create(name: "DJ Chark", position: "WR")
Player.create(name: "Devin Singletary", position: "WR")
Player.create(name: "Raheem Mostert", position: "WR")
Player.create(name: "Zach Ertz", position: "TE")
Player.create(name: "Dak Prescott", position: "QB")
Player.create(name: "DK Metcalf", position: "WR")
Player.create(name: "Terry McLaurin", position: "WR")
Player.create(name: "David Johnson", position: "RB")
Player.create(name: "James White", position: "RB")
Player.create(name: "Russell Wilson", position: "QB")
Player.create(name: "Darren Waller", position: "TE")
Player.create(name: "Deebo Samuel", position: "WR")
Player.create(name: "D'Andre Swift", position: "RB")
Player.create(name: "Kyler Murray", position: "QB")
Player.create(name: "Mark Ingram", position: "RB")
Player.create(name: "Tyler Boyd", position: "WR")
Player.create(name: "Evan Engram", position: "TE")
Player.create(name: "Deshaun Watson", position: "QB")
Player.create(name: "Jarvis Landry", position: "WR")
Player.create(name: "Michael Gallup", position: "WR")
Player.create(name: "Hunter Henry", position: "TE")
Player.create(name: "Cam Akers", position: "RB")
Player.create(name: "Josh Allen", position: "QB")
Player.create(name: "Rob Gronkowski", position: "TE")
Player.create(name: "Austin Hooper", position: "TE")
Player.create(name: "Julian Edelman", position: "WR")
Player.create(name: "Stephen Gostkowski", position: "K")
Player.create(name: "Justin Tucker", position: "K")
Player.create(name: "Harrison Butker", position: "K")
Player.create(name: "Rodrigo Blankenship", position: "K")
Player.create(name: "Matt Prater", position: "K")
Player.create(name: "Steven Haushcka", position: "K")
Player.create(name: "Sebastian Janikowski", position: "K")
Player.create(name: "Adam Vinatieri", position: "K")
Player.create(name: "Jake Elliot", position: "K")
Player.create(name: "Younghoe Koo", position: "K")
Player.create(name: "Bears", position: "D")
Player.create(name: "Steelers", position: "D")
Player.create(name: "Eagles", position: "D")
Player.create(name: "Cardinals", position: "D")
Player.create(name: "Chiefs", position: "D")
Player.create(name: "Saints", position: "D")
Player.create(name: "Rams", position: "D")
Player.create(name: "Chargers", position: "D")
Player.create(name: "Ravens", position: "D")
Player.create(name: "Falcons", position: "D")






100.times do
  PlayerTeam.create(player_id: Player.all.sample.id, team_id: Team.all.sample.id)
end

100.times do
  Ranking.create(analyst_id: rand(4..6), player_id: Player.all.sample.id, ranking: rand(1..100))
end
